[versions]
agp = "8.13.2"
kotlin = "2.3.0"
zygoteloader = "bf5078e182"
r8-annotations = "v1.0.1"
shadowhook = "2.0.1"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
zygoteloader = { id = "com.github.aerath-stuff.ZygoteLoader", version.ref = "zygoteloader" }

[libraries]
r8-annotations = { module = "io.github.vova7878:R8Annotations", version.ref = "r8-annotations" }
androidx-annotation-jvm = { module = "androidx.annotation:annotation-jvm", version = "1.10.0" }
shadowhook = { module = "com.bytedance.android:shadowhook", version.ref = "shadowhook" }
